# Generated by Django 4.2.1 on 2023-07-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('DO_Birth', models.CharField(max_length=30)),
                ('DO_Joining', models.CharField(max_length=67)),
                ('DO_Anniversary', models.CharField(max_length=59)),
                ('Email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
